export const speakerData = [
  {
    id: 1,
    name_ka: 'დინა გუსეინოვა',
    name_en: 'Dina Guseynova',
    panel_ka: 'დეზინფორმაცია და ხარისხიანი განათლების ხელმისაწვდომობა ციფრულ ეპოქაში',
    panel_eng: 'Disinformation and Accessibility of Quality Education in Digital Era',
    position_ka: 'საერთაშორისო ისტორიის კათედრის ასოცირებული პროფესორი',
    position_eng: 'Associate Professor at Department of International History',
    image: '/assets/DinaGusejnova.png',
    company_ka: 'LSE',
    company_eng: 'LSE',
    color: '#FF7B00',
  },
  {
    id: 2,
    name_ka: 'მეთიუ მურაი',
    name_en: 'Matthew Murray',
    panel_ka: 'ეკონომიკური გაურკვევლობა და ტვინების გადინება',
    panel_eng: 'Economic Uncertainty and Brain Drain',
    position_ka: 'საერთაშორისო და საზოგადოებრივ საქმეთა ასიუნტ პროფესორი',
    position_eng: 'Adjunct Professor of International and Public Affairs',
    image: '/assets/MatthewMurray.png',
    company_ka: 'SIPA Columbia',
    company_eng: 'SIPA Columbia',
    color: '#D70000',
  },
  {
    id: 3,
    name_ka: 'პიტერ კლემენტი',
    name_en: 'Peter Clement',
    panel_ka: 'ახალგაზრდების პოლიტიკური მონაწილეობა და წარმომადგენლობა',
    panel_eng: 'Political Participation and Representation of youth ',
    position_ka:
      'არნოლდ ა. სოლცმანის ომისა და მშვიდობის კვლევების ინსტიტუტის არნოლდ ა. სოლცმანის მოწვეული უფროსი მკვლევარი; დამხმარე პროფესორი',
    position_eng:
      'Visiting Senior Research Scholar in the Arnold A. Saltzman Institute of War and Peace Studies; Adjunct Professor',
    image: '/assets/PeterClement.png',
    company_ka: 'SIPA Columbia',
    company_eng: 'SIPA Columbia',
    color: '#32A800',
  },
  {
    id: 4,
    name_ka: 'სვეტა პეტროვა',
    name_en: 'Tsveta Petrova',
    panel_ka: 'დეზინფორმაცია და ხარისხიანი განათლების ხელმისაწვდომობა ციფრულ ეპოქაში',
    panel_eng: 'Disinformation and Accessibility of Quality Education in Digital Era',
    position_ka: 'პოლიტიკური მეცნიერების დისციპლინის ლექტორი',
    position_eng: 'Lecturer in the Discipline of Political Science',
    image: '/assets/TsvetaPetrova.png',
    company_ka: 'Columbia University',
    company_eng: 'Columbia University',
    color: '#FF7B00',
  },
];
